services:
  
  db:
    container_name: db
    image: mysql:8
    restart: always
    env_file:
      - .env
    volumes:
      - ./dbdata:/var/lib/mysql/
    networks:
      - app-net

  frontend: 
    container_name: frontend
    build: 
      context: ./react-frontend
      dockerfile: Dockerfile
    env_file:
      - ./react-frontend/.env
    volumes:
      - frontend-build:/app/build
    networks:
      - app-net

  backend: 
    container_name: backend
    build:
      context: ./spring-backend
      dockerfile: Dockerfile
    env_file: 
      - ./spring-backend/.env
    networks:
      - app-net
    depends_on:
      - db

  nginx-proxy:
    container_name: nginx-proxy
    image: nginx:alpine
    ports:
      - "3000:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend-build:/usr/share/nginx/html:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-net
    # user: "nginx:nginx"

volumes:
  frontend-build:
  db-data:

networks:
  app-net:
    driver: bridge