services:
  postgres:
    image: postgres:13-alpine3.20
    environment:
      POSTGRES_DB: "listmonk"
      POSTGRES_USER: "listmonk"
      POSTGRES_PASSWORD: "listmonk"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U listmonk -d listmonk"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    
  listmonk:
    build: .
    depends_on:
      - postgres
    volumes:
      - ./listmonk/static:/app/listmonk/static
    environment:
      APP_ADDRESS: "0.0.0.0:9000"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_USER: "listmonk"
      DB_PASSWORD: "listmonk"
      DB_NAME: "listmonk"
      DB_SSL_MODE: "disable"
      DB_MAX_OPEN: "25"
      DB_MAX_IDLE: "25"
      DB_MAX_LIFETIME: "300s"
    ports:
      - "9000:9000"

volumes:
  postgres_data: